webhotel/clientes/urls.py
from django.urls import path
from . import views


app_name = "clientes"
urlpatterns = [
    path('clientes/', views.agregar_clientes, name="agregar_clientes"),
    path('listar_clientes/', views.listar_c, name="lista_cliente"),
    path('delete/<str:cliente_id>/', views.eliminar_clientes, name='eliminar_cliente'),
    path('update/<int:cliente_id>/', views.actualizar_cliente, name='clientes_actuali'),

]

webhotel/inicio/urls.py
from django.urls import path
from . import views

app_name = "inicio"
urlpatterns = [

#---------------------ACTAS MATRIMONIALES------------------------    
    path('home/', views.home, name="activi"),


    

]

webhotel/registro/urls.py
from django.urls import path
from . import views


app_name = "registro"
urlpatterns = [
    path('registro/', views.agregar_registro, name="agregar_registro"),
    path('listar_registro/', views.listar_r, name="lista_registro"),
    path('delete/<str:registro_id>/', views.eliminar_registro, name='eliminar_registro'),
    path('update/<int:registro_id>/', views.actualizar_registro, name='registro_actuali'),

]

webhotel/webhotel/urls.py
from django.contrib import admin
from django.urls import path, include
from inicio import views as view_m

urlpatterns = [
     path('SCHotel/', admin.site.urls),
     path('inicios/', include('inicio.urls')),
     path('', include('auntenticacion.urls')),
     path('clientes/', include('clientes.urls')),
     path('habitaciones/', include('habitaciones.urls')),
     path('registro/', include('registro.urls')),
     path('rerservaciones/', include('reservaciones.urls')),
     #path('admin/', admin.site.urls),
     path('',view_m.home, name="home"),
]

webhotel/registro/models.py
from django.db import models
from clientes.models import cliente
from habitaciones.models import habitacion

 
class registrohabitaciones(models.Model):
    clienteregistro = models.ForeignKey(cliente, on_delete=models.CASCADE)
    habitacionregistro= models.ForeignKey(habitacion, on_delete=models.CASCADE)
    entrada = models.DateTimeField(max_length=50, verbose_name="Entrada")
    salida = models.DateTimeField(max_length=50, null=True, verbose_name="Salida")
    
    
    def __str__(self):
        return self.nombre
    
    class Meta:
       db_table ='registrohabitacion'
       verbose_name= 'registrohabitacion'
       verbose_name_plural= 'registrohabitaciones'
       ordering = ['-id']      

webhotel/registro/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.db.models import Q
from .models import registrohabitaciones
from clientes.models import cliente
from habitaciones.models import habitacion, estado
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from django.db import transaction

@login_required(login_url="auth/login/")
def agregar_registro(request):
    Clientes = cliente.objects.all()
    estado_ocupada = get_object_or_404(estado, nombre='Ocupada')
    
    # Obtener el estado "Desocupada" por su nombre
    estado_desocupada = get_object_or_404(estado, nombre='Desocupada')

    # Filtrar las habitaciones por estado "Desocupada"
    Habitaciones = habitacion.objects.filter(estado=estado_desocupada)

    if request.method == 'POST':
        cliente_id = request.POST.get('Clientes')
        habitacion_id = request.POST.get('Habitaciones')
        salida = request.POST.get('salida')  # Este puede ser opcional

        # Establecer fecha y entrada automáticamente
        entrada = timezone.now()  # Fecha y hora actuales

        # Validaciones
        if not all([cliente_id, habitacion_id]):
            messages.error(request, 'Los campos Cliente y Habitacion son obligatorios.', extra_tags="danger")
            return redirect('registro:agregar_registro')


        # Crear nuevo registro
        try:
            with transaction.atomic():  # Asegura que ambas operaciones se completen correctamente
                registro = registrohabitaciones(
                    clienteregistro_id=cliente_id,
                    habitacionregistro_id=habitacion_id,
                    entrada=entrada,
                    salida=salida if salida else None,  # Almacena 'None' si no hay salida
                )
                registro.save()

                # Cambiar el estado de la habitación a "Ocupada"
                habitacion_obj = get_object_or_404(habitacion, id=habitacion_id)
                habitacion_obj.estado = estado_ocupada
                habitacion_obj.save()

            messages.success(request, 'Registro de habitación creado con éxito y habitación marcada como ocupada!', extra_tags="success")
            return redirect('registro:lista_registro')

        except Exception as e:
            messages.error(request, 'Error al crear el registro: ' + str(e), extra_tags="danger")
            return redirect('registro:agregar_registro')

    return render(request, "registro/registro.html", {'Clientes': Clientes, 'Habitaciones': Habitaciones})



def listar_r(request):
    query = request.GET.get('q', '')
    registros_list = registrohabitaciones.objects.filter(
        Q(clienteregistro__nombre__icontains=query) |
        Q(habitacionregistro__nohabitacion__icontains=query) |
        Q(entrada__icontains=query) |
        Q(salida__icontains=query)    
    )

    context = {
        "active_icon": "registro_habitacion",
        "registros": registros_list,
        "query": query,
    }
    return render(request, "registro/listar_registro.html", context)




@login_required(login_url="auth/login/")
def eliminar_registro(request, registro_id):
    try:
        registro = registrohabitaciones.objects.get(pk=registro_id)
        habitacion_obj = registro.habitacionregistro  # Obtener la habitación asociada

        # Cambiar el estado de la habitación a "Desocupada"
        estado_desocupada = get_object_or_404(estado, nombre='Desocupada')
        habitacion_obj.estado = estado_desocupada
        habitacion_obj.save()

        # Eliminar el registro
        registro.delete()
        messages.success(request, '¡Registro de habitación eliminado y habitación marcada como desocupada!', extra_tags="success")

    except registrohabitaciones.DoesNotExist:
        messages.error(request, 'El registro no existe.', extra_tags="danger")
    except Exception as e:
        messages.error(request, '¡Hubo un error durante la eliminación! ' + str(e), extra_tags="danger")

    return redirect('registro:lista_registro')





@login_required(login_url="auth/login/")
def actualizar_registro(request, registro_id):
    try:
        registro = registrohabitaciones.objects.get(id=registro_id)

        if request.method == 'POST':
            # Cambiar el estado de la habitación a "Desocupada"
            estado_desocupada = get_object_or_404(estado, nombre='Desocupada')
            habitacion_anterior = registro.habitacionregistro
            
            if habitacion_anterior:
                habitacion_anterior.estado = estado_desocupada
                habitacion_anterior.save()

            # Actualiza la salida a la fecha y hora actuales
            registro.salida = timezone.now()  # Establece la salida a la fecha y hora actuales
            registro.save()

            # Mostrar mensaje de éxito
            messages.success(request, 'Habitación desocupada y registro cerrado con éxito!', extra_tags="success")

            # Redirigir a la lista de registros
            return redirect('registro:lista_registro')

    except registrohabitaciones.DoesNotExist:
        messages.error(request, 'El registro no existe.', extra_tags="danger")
    except Exception as e:
        messages.error(request, '¡Hubo un error durante la actualización: ' + str(e), extra_tags="danger")

    return redirect('registro:lista_registro')

webhotel/templates/registro/actualizar_registro.html
{% extends 'base/base.html' %}
{% load static %}
{% block stylesheets %}
<link href="{% static 'mie/css/miembros.css' %}" rel="stylesheet" type="text/css">
{% endblock stylesheets %}
{% block title %} Actualizar Miembro {% endblock %}
{% block background %}{% static 'mie/img/musulman.jpg' %}{% endblock %}

{% block headers %}
<h1>Actualizar Miembro</h1>
{% endblock %}

{% block content %}
<div class="member-section">
    <form method="post">
        {% csrf_token %}

        <div class="form-group-container">
            <div class="form-group">
                <label for="nombre">Nombres:</label>
                <input type="text" id="nombre" name="nombre" class="form-control" required value="{{ cliente.nombre }}">
            </div>
            <div class="form-group">
                <label for="apellidos">Apellidos:</label>
                <input type="text" id="apellidos" name="apellidos" class="form-control" required value="{{ cliente.apellido }}">
            </div>
        </div>

        <div class="form-group-container">
            <div class="select-group" style="margin-right: auto;">
                <label for="genero">Género:</label>
                <select id="genero" name="genero" class="form-control" required>
                    <option value="" disabled selected>Selecciona un género</option>
                    {% for g in generos %}
                        <option value="{{ g.id }}" {% if g.id == cliente.genero.id %}selected{% endif %}>
                            {{ g.nombre }}
                        </option>
                    {% endfor %}
                </select>
            </div>

        </div>

        <div class="form-group-container">
            <div class="form-group">
            <label for="dpi">DPI:</label>
            <input type="text" id="dpi" name="dpi" class="form-control" required value="{{ cliente.dpi }}">
            </div>
        </div>

        <div class="form-group-container">
            <div class="form-group">
                <label for="telefono">Teléfono:</label>
                <input type="number" id="telefono" name="telefono" class="form-control" required value="{{ cliente.telefono }}">
            </div>
        </div>


        <div class="button-group">
            <button style= "cursor: pointer;"  type="submit" class="btn btn-primary agregar-button">ACTUALIZAR</button>
            <a href="{% url 'clientes:lista_cliente' %}" class="btn btn-primary listar-button">Listar</a>
        </div>
    </form>
</div>
{% endblock %}

webhotel/templates/registro/listar_registro.html
{% extends 'base/base.html' %}
{% load static %}
{% block stylesheets %}
<link href="{% static 'mie/css/listar_miembros.css' %}" rel="stylesheet" type="text/css">
{% endblock stylesheets %}

{% block title %}Registros{% endblock %}

{% block background %}{% static 'mie/img/registro.jpg' %}{% endblock %}

{% block headers %}<h1>Lista de Registros</h1>{% endblock %}

{% block content %}

<div class="row ml-0 mb-3">
    <a href="{% url 'registro:agregar_registro' %}">
        <button  style= "cursor: pointer;" type="button" class="btn btn-info font-weight-bold">
            <i class="fas fa-long-arrow-alt-left mr-2"></i>
            AGREGAR REGISTRO
        </button>
    </a>
</div>
<div style="background-color: rgba(0, 0, 0, 0.1); color: #757070; padding: 10px; margin: 10px 0;">
    Total de Registros: {{ registros|length }}
</div> 
<div class="content-container">
    <form method="get" action="{% url 'registro:lista_registro' %}">
        <div class="search-bar">
            <input type="text" name="q" class="form-control" placeholder="Buscar" value="{{ query }}" id="search-input">
        </div>
    </form>
    <div id="custom-table" class="table-responsive">
        <table class="custom-table">
            <thead>
                <tr>
                    <th>Cliente</th>
                    <th>Habitacion</th>
                    <th>Estrada</th>
                    <th>Salida</th>

                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for registro in registros %}
                    <tr>
                        <td>{{ registro.clienteregistro.nombre }}</td>
                        <td>{{ registro.habitacionregistro.nohabitacion }}</td>
                        <td>{{ registro.entrada }}</td>
                        <td>{{ registro.salida }}</td>
                            <td class="acciones">
                                <div>
                                    {% if registro.salida %}
                                        <!-- Si ya hay una fecha de salida, se muestra un mensaje o se desactiva el botón -->
                                        <button class="btn btn-success" disabled title="Registro cerrado">
                                            CERRAR
                                        </button>
                                    {% else %}
                                        <!-- Si no hay fecha de salida, muestra el botón para cerrar -->
                                        <form method="POST" action="{% url 'registro:registro_actuali' registro.id %}">
                                            {% csrf_token %}
                                            <button type="submit" style="cursor: pointer;" class="btn btn-success" title="Cerrar registro">
                                                CERRAR
                                            </button>
                                        </form>
                                    {% endif %}
                                <a href="#" class="btn btn-danger" data-toggle="modal" data-target="#eliminarCliente{{ registro.id }}">
                                   ELIMINAR
                                </a>
                            </div>
                            <div class="modal fade" id="eliminarCliente{{ registro.id }}" tabindex="-1" aria-labelledby="exampleModalLabel{{ registro.id }}" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">  
                                            <h5 class="modal-title" id="exampleModalLabel{{ cliente.id }}">Eliminar Registro</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            ¿Está seguro que desea eliminar a: {{ registro.clienteregistro.nombre }}?
                                        </div>
                                        <div class="modal-footer">
                                            <button style="cursor: pointer;" type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                                            <a id="updateThisURL" rel="delete" href="{% url 'registro:eliminar_registro' registro.id %}" class="btn btn-danger text-decoration-none">Eliminar</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </td>

                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}
{% block javascripts %}
<script src="{% static 'tables/js/jquery-3.7.0.js' %}"></script>
<script>
document.addEventListener('DOMContentLoaded', function () {
    const searchInput = document.getElementById('search-input');
    const tableRows = document.querySelectorAll('.custom-table tbody tr');

    searchInput.addEventListener('input', function () {
        const query = searchInput.value.toLowerCase();

        tableRows.forEach(function (row) {
            const cells = row.querySelectorAll('td');
            let found = false;

            cells.forEach(function (cell) {
                const cellText = cell.innerText.toLowerCase();
                if (cellText.includes(query)) {
                    found = true;
                }
            });

            if (found) {
                row.style.display = '';
            } else {
                row.style.display = 'none';
            }
        });
    });
});
</script>
{% endblock javascripts %}

webhotel/templates/registro/registro.html
{% extends 'base/base.html' %}
{% load static %}
{% block stylesheets %}
<link href="{% static 'mie/css/miembros.css' %}" rel="stylesheet" type="text/css">
{% endblock stylesheets %}

{% block title %} Registros {% endblock %}

{% block background %}{% static 'mie/img/registro.jpg' %}{% endblock %}

{% block headers %}
<h1>Registros</h1>
{% endblock %}

{% block content %}
<div class="member-section">
    <div id="alert-message" style="display: none;"></div>

    <form method="post" id="miembro-form">
        {% csrf_token %}
        <div class="form-group-container">
            <div class="form-group">
                <label for="Clientes">Cliente:</label>
                <select id="Clientes" name="Clientes" class="form-control" required>
                    <option value="" disabled selected>Selecciona un Cliente</option>
                    {% for eve in Clientes %}
                        <option value="{{ eve.id }}">{{ eve.nombre }} {{ eve.apellido }}</option>
                    {% endfor %}
                </select>
            </div>
          </div>    

        <div class="form-group-container">
            <div class="select-group" >
                <label for="Habitaciones">Habitacion:</label>
                <select id="Habitaciones" name="Habitaciones" class="form-control" required>
                    <option value="" disabled selected>Selecciona una Habitacion</option>
                    {% for g in Habitaciones %}
                        <option value="{{ g.id }}">{{ g.nohabitacion }}</option>
                    {% endfor %}
                </select>
            </div>
            
           
        </div>


        <div class="button-group">
            <button style= "cursor: pointer;" type="submit" class="btn btn-primary agregar-button">Agregar</button>
            <a href="{% url 'registro:lista_registro' %}" class="btn btn-primary listar-button">Listar</a>
        </div>
    </form>
</div>
{% endblock %}