webhotel/clientes/urls.py
from django.urls import path
from . import views


app_name = "clientes"
urlpatterns = [
    path('clientes/', views.agregar_clientes, name="agregar_clientes"),
    path('listar_clientes/', views.listar_c, name="lista_cliente"),
    path('delete/<str:cliente_id>/', views.eliminar_clientes, name='eliminar_cliente'),
    path('update/<int:cliente_id>/', views.actualizar_cliente, name='clientes_actuali'),

]

webhotel/inicio/urls.py
from django.urls import path
from . import views

app_name = "inicio"
urlpatterns = [

#---------------------ACTAS MATRIMONIALES------------------------    
    path('home/', views.home, name="activi"),


    

]

webhotel/reservaciones/urls.py
from django.urls import path
from . import views


app_name = "reservaciones"
urlpatterns = [
    path('reservacion/', views.agregar_reservacion, name="agregar_reservacion"),
    path('listar_reservacion/', views.listar_re, name="lista_reservacion"),
    path('delete/<str:reservacion_id>/', views.eliminar_reservacion, name='eliminar_reservacion'),
    path('update/<int:reservacion_id>/', views.actualizar_reservacion, name='reservacion_actuali'),

]

webhotel/webhotel/urls.py
from django.contrib import admin
from django.urls import path, include
from inicio import views as view_m

urlpatterns = [
     path('SCHotel/', admin.site.urls),
     path('inicios/', include('inicio.urls')),
     path('', include('auntenticacion.urls')),
     path('clientes/', include('clientes.urls')),
     path('habitaciones/', include('habitaciones.urls')),
     path('registro/', include('registro.urls')),
     path('rerservaciones/', include('reservaciones.urls')),
     #path('admin/', admin.site.urls),
     path('',view_m.home, name="home"),
]

webhotel/templates/reservacion/actualizar_reservacion.html
{% extends 'base/base.html' %}
{% load static %}
{% block stylesheets %}
<link href="{% static 'mie/css/miembros.css' %}" rel="stylesheet" type="text/css">
{% endblock stylesheets %}
{% block title %} Actualizar Miembro {% endblock %}
{% block background %}{% static 'mie/img/musulman.jpg' %}{% endblock %}

{% block headers %}
<h1>Actualizar Miembro</h1>
{% endblock %}

{% block content %}
<div class="member-section">
    <form method="post">
        {% csrf_token %}

        <div class="form-group-container">
            <div class="form-group">
                <label for="nombre">Nombres:</label>
                <input type="text" id="nombre" name="nombre" class="form-control" required value="{{ cliente.nombre }}">
            </div>
            <div class="form-group">
                <label for="apellidos">Apellidos:</label>
                <input type="text" id="apellidos" name="apellidos" class="form-control" required value="{{ cliente.apellido }}">
            </div>
        </div>

        <div class="form-group-container">
            <div class="select-group" style="margin-right: auto;">
                <label for="genero">Género:</label>
                <select id="genero" name="genero" class="form-control" required>
                    <option value="" disabled selected>Selecciona un género</option>
                    {% for g in generos %}
                        <option value="{{ g.id }}" {% if g.id == cliente.genero.id %}selected{% endif %}>
                            {{ g.nombre }}
                        </option>
                    {% endfor %}
                </select>
            </div>

        </div>

        <div class="form-group-container">
            <div class="form-group">
            <label for="dpi">DPI:</label>
            <input type="text" id="dpi" name="dpi" class="form-control" required value="{{ cliente.dpi }}">
            </div>
        </div>

        <div class="form-group-container">
            <div class="form-group">
                <label for="telefono">Teléfono:</label>
                <input type="number" id="telefono" name="telefono" class="form-control" required value="{{ cliente.telefono }}">
            </div>
        </div>


        <div class="button-group">
            <button style= "cursor: pointer;"  type="submit" class="btn btn-primary agregar-button">ACTUALIZAR</button>
            <a href="{% url 'clientes:lista_cliente' %}" class="btn btn-primary listar-button">Listar</a>
        </div>
    </form>
</div>
{% endblock %}

webhotel/templates/reservacion/listar_reservacion.html
{% extends 'base/base.html' %}
{% load static %}
{% block stylesheets %}
<link href="{% static 'mie/css/listar_miembros.css' %}" rel="stylesheet" type="text/css">
{% endblock stylesheets %}

{% block title %}Reservaciones{% endblock %}

{% block background %}{% static 'mie/img/reservacion.jpg' %}{% endblock %}

{% block headers %}<h1>Lista de Reservaciones</h1>{% endblock %}

{% block content %}

<div class="row ml-0 mb-3">
    <a href="{% url 'reservaciones:agregar_reservacion' %}">
        <button  style= "cursor: pointer;" type="button" class="btn btn-info font-weight-bold">
            <i class="fas fa-long-arrow-alt-left mr-2"></i>
            AGREGAR RESERVACION
        </button>
    </a>
</div>
<div style="background-color: rgba(0, 0, 0, 0.1); color: #757070; padding: 10px; margin: 10px 0;">
    Total de Registros: {{ reservaciones|length }}
</div> 
<div class="content-container">
    <form method="get" action="{% url 'reservaciones:lista_reservacion' %}">
        <div class="search-bar">
            <input type="text" name="q" class="form-control" placeholder="Buscar" value="{{ query }}" id="search-input">
        </div>
    </form>
    <div id="custom-table" class="table-responsive">
        <table class="custom-table">
            <thead>
                <tr>
                    <th>Cliente</th>
                    <th>Habitacion</th>
                    <th>Fecha</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for reservacion in reservaciones %}
                    <tr>
                        <td>{{ reservacion.clientereservacion.nombre }}</td>
                        <td>{{ reservacion.habitacionreservacion.nohabitacion }}</td>
                        <td>{{ reservacion.fechareservacion }}</td>
                            <td class="acciones">
                                <div>
                                        <!-- Si no hay fecha de salida, muestra el botón para cerrar -->
                                        <form method="POST" action="{% url 'reservaciones:reservacion_actuali' reservacion.id %}">
                                            {% csrf_token %}
                                            <button type="submit" style="cursor: pointer;" class="btn btn-success" title="Cerrar registro">
                                                CERRAR
                                            </button>
                                        </form>
                                 
                                <a href="#" class="btn btn-danger" data-toggle="modal" data-target="#eliminarCliente{{ reservacion.id }}">
                                   ELIMINAR
                                </a>
                            </div>
                            <div class="modal fade" id="eliminarCliente{{ reservacion.id }}" tabindex="-1" aria-labelledby="exampleModalLabel{{ reservacion.id }}" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">  
                                            <h5 class="modal-title" id="exampleModalLabel{{ cliente.id }}">Eliminar Reservacion</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            ¿Está seguro que desea eliminar a: {{ reservacion.clientereservacion.nombre }}?
                                        </div>
                                        <div class="modal-footer">
                                            <button style="cursor: pointer;" type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                                            <a id="updateThisURL" rel="delete" href="{% url 'reservaciones:eliminar_reservacion' reservacion.id %}" class="btn btn-danger text-decoration-none">Eliminar</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </td>

                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}
{% block javascripts %}
<script src="{% static 'tables/js/jquery-3.7.0.js' %}"></script>
<script>
document.addEventListener('DOMContentLoaded', function () {
    const searchInput = document.getElementById('search-input');
    const tableRows = document.querySelectorAll('.custom-table tbody tr');

    searchInput.addEventListener('input', function () {
        const query = searchInput.value.toLowerCase();

        tableRows.forEach(function (row) {
            const cells = row.querySelectorAll('td');
            let found = false;

            cells.forEach(function (cell) {
                const cellText = cell.innerText.toLowerCase();
                if (cellText.includes(query)) {
                    found = true;
                }
            });

            if (found) {
                row.style.display = '';
            } else {
                row.style.display = 'none';
            }
        });
    });
});
</script>
{% endblock javascripts %}

webhotel/templates/reservacion/reservacion.html
{% extends 'base/base.html' %}
{% load static %}
{% block stylesheets %}
<link href="{% static 'mie/css/miembros.css' %}" rel="stylesheet" type="text/css">
{% endblock stylesheets %}

{% block title %} Reservaciones {% endblock %}

{% block background %}{% static 'mie/img/reservacion.jpg' %}{% endblock %}

{% block headers %}
<h1>Reservaciones</h1>
{% endblock %}

{% block content %}
<div class="member-section">
    <div id="alert-message" style="display: none;"></div>

    <form method="post" id="miembro-form">
        {% csrf_token %}
        <div class="form-group-container">
            <div class="form-group">
                <label for="Clientes">Cliente:</label>
                <select id="Clientes" name="Clientes" class="form-control" required>
                    <option value="" disabled selected>Selecciona un Cliente</option>
                    {% for eve in Clientes %}
                        <option value="{{ eve.id }}">{{ eve.nombre }} {{ eve.apellido }}</option>
                    {% endfor %}
                </select>
            </div>
          </div>    

        <div class="form-group-container">
            <div class="select-group" >
                <label for="Habitaciones">Habitacion:</label>
                <select id="Habitaciones" name="Habitaciones" class="form-control" required>
                    <option value="" disabled selected>Selecciona una Habitacion</option>
                    {% for g in Habitaciones %}
                        <option value="{{ g.id }}">{{ g.nohabitacion }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>   


        <div class="form-group-container">
            <div class="form-group">
                <label for="fechareservacion">Fecha:</label>
                <input type="date" id="fechareservacion" name="fechareservacion" class="form-control" required>
            </div>
            
           
        </div>

    
       

        <div class="button-group">
            <button style= "cursor: pointer;" type="submit" class="btn btn-primary agregar-button">Agregar</button>
            <a href="{% url 'reservaciones:lista_reservacion' %}" class="btn btn-primary listar-button">Listar</a>
        </div>
    </form>
</div>
{% endblock %}