webhotel/clientes/urls.py
from django.urls import path
from . import views


app_name = "clientes"
urlpatterns = [
    path('clientes/', views.agregar_clientes, name="agregar_clientes"),
    path('listar_clientes/', views.listar_c, name="lista_cliente"),
    path('delete/<str:cliente_id>/', views.eliminar_clientes, name='eliminar_cliente'),
    path('update/<int:cliente_id>/', views.actualizar_cliente, name='clientes_actuali'),

]

webhotel/inicio/urls.py
from django.urls import path
from . import views

app_name = "inicio"
urlpatterns = [

#---------------------ACTAS MATRIMONIALES------------------------    
    path('home/', views.home, name="activi"),


    

]

webhotel/webhotel/urls.py
from django.contrib import admin
from django.urls import path, include
from inicio import views as view_m

urlpatterns = [
     path('SCHotel/', admin.site.urls),
     path('inicios/', include('inicio.urls')),
     path('', include('auntenticacion.urls')),
     path('clientes/', include('clientes.urls')),
     path('habitaciones/', include('habitaciones.urls')),
     path('registro/', include('registro.urls')),
     path('rerservaciones/', include('reservaciones.urls')),
     #path('admin/', admin.site.urls),
     path('',view_m.home, name="home"),
]

webhotel/templates/miembro/actualizar_miembros.html
{% extends 'base/base.html' %}
{% load static %}
{% block stylesheets %}
<link href="{% static 'mie/css/miembros.css' %}" rel="stylesheet" type="text/css">
{% endblock stylesheets %}
{% block title %} Actualizar Miembro {% endblock %}
{% block background %}{% static 'mie/img/cliente.jpg' %}{% endblock %}

{% block headers %}
<h1>Actualizar Miembro</h1>
{% endblock %}

{% block content %}
<div class="member-section">
    <form method="post">
        {% csrf_token %}

        <div class="form-group-container">
            <div class="form-group">
                <label for="nombre">Nombres:</label>
                <input type="text" id="nombre" name="nombre" class="form-control" required value="{{ cliente.nombre }}">
            </div>
            <div class="form-group">
                <label for="apellidos">Apellidos:</label>
                <input type="text" id="apellidos" name="apellidos" class="form-control" required value="{{ cliente.apellido }}">
            </div>
        </div>

        <div class="form-group-container">
            <div class="select-group" style="margin-right: auto;">
                <label for="genero">Género:</label>
                <select id="genero" name="genero" class="form-control" required>
                    <option value="" disabled selected>Selecciona un género</option>
                    {% for g in generos %}
                        <option value="{{ g.id }}" {% if g.id == cliente.genero.id %}selected{% endif %}>
                            {{ g.nombre }}
                        </option>
                    {% endfor %}
                </select>
            </div>

        </div>

        <div class="form-group-container">
            <div class="form-group">
            <label for="dpi">DPI:</label>
            <input type="text" id="dpi" name="dpi" class="form-control" required value="{{ cliente.dpi }}">
            </div>
        </div>

        <div class="form-group-container">
            <div class="form-group">
                <label for="telefono">Teléfono:</label>
                <input type="number" id="telefono" name="telefono" class="form-control" required value="{{ cliente.telefono }}">
            </div>
        </div>


        <div class="button-group">
            <button style= "cursor: pointer;"  type="submit" class="btn btn-primary agregar-button">ACTUALIZAR</button>
            <a href="{% url 'clientes:lista_cliente' %}" class="btn btn-primary listar-button">Listar</a>
        </div>
    </form>
</div>
{% endblock %}

webhotel/templates/miembro/listar_miembros.html
{% extends 'base/base.html' %}
{% load static %}
{% block stylesheets %}
<link href="{% static 'mie/css/listar_miembros.css' %}" rel="stylesheet" type="text/css">
{% endblock stylesheets %}

{% block title %}Clientes{% endblock %}

{% block background %}{% static 'mie/img/cliente.jpg' %}{% endblock %}

{% block headers %}<h1>Lista de Clientes</h1>{% endblock %}

{% block content %}

<div class="row ml-0 mb-3">
    <a href="{% url 'clientes:agregar_clientes' %}">
        <button  style= "cursor: pointer;" type="button" class="btn btn-info font-weight-bold">
            <i class="fas fa-long-arrow-alt-left mr-2"></i>
            AGREGAR CLIENTE
        </button>
    </a>
</div>
<div style="background-color: rgba(0, 0, 0, 0.1); color: #757070; padding: 10px; margin: 10px 0;">
    Total de Registros: {{ clientes|length }}
</div> 
<div class="content-container">
    <form method="get" action="{% url 'clientes:lista_cliente' %}">
        <div class="search-bar">
            <input type="text" name="q" class="form-control" placeholder="Buscar" value="{{ query }}" id="search-input">
        </div>
    </form>
    <div id="custom-table" class="table-responsive">
        <table class="custom-table">
            <thead>
                <tr>
                    <th>Nombres</th>
                    <th>Apellidos</th>
                    <th>DPI</th>
                    <th>Teléfono</th>
                    <th>Género</th>

                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for cliente in clientes %}
                    <tr>
                        <td>{{ cliente.nombre }}</td>
                        <td>{{ cliente.apellido }}</td>
                        <td>{{ cliente.dpi }}</td>
                        <td>{{ cliente.telefono }}</td>
                        <td>{{ cliente.genero.nombre }}</td>
                        <td class="acciones">
                            <div>
                                <a href="{% url 'clientes:clientes_actuali' cliente.id %}" class="btn btn-success" title="Actualizar cliente">
                                   ACTUALIZAR
                                </a>
                                <a href="#" class="btn btn-danger" data-toggle="modal" data-target="#eliminarCliente{{ cliente.id }}">
                                   ELIMINAR
                                </a>
                            </div>
                            <div class="modal fade" id="eliminarCliente{{ cliente.id }}" tabindex="-1" aria-labelledby="exampleModalLabel{{ cliente.id }}" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">  
                                            <h5 class="modal-title" id="exampleModalLabel{{ cliente.id }}">Eliminar Cliente</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            ¿Está seguro que desea eliminar a: {{cliente.nombre }}?
                                        </div>
                                        <div class="modal-footer">
                                            <button style="cursor: pointer;" type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                                            <a id="updateThisURL" rel="delete" href="{% url 'clientes:eliminar_cliente' cliente.id %}" class="btn btn-danger text-decoration-none">Eliminar</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </td>

                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}
{% block javascripts %}
<script src="{% static 'tables/js/jquery-3.7.0.js' %}"></script>
<script>
document.addEventListener('DOMContentLoaded', function () {
    const searchInput = document.getElementById('search-input');
    const tableRows = document.querySelectorAll('.custom-table tbody tr');

    searchInput.addEventListener('input', function () {
        const query = searchInput.value.toLowerCase();

        tableRows.forEach(function (row) {
            const cells = row.querySelectorAll('td');
            let found = false;

            cells.forEach(function (cell) {
                const cellText = cell.innerText.toLowerCase();
                if (cellText.includes(query)) {
                    found = true;
                }
            });

            if (found) {
                row.style.display = '';
            } else {
                row.style.display = 'none';
            }
        });
    });
});
</script>
{% endblock javascripts %}

webhotel/templates/miembro/miembros.html
{% extends 'base/base.html' %}
{% load static %}
{% block stylesheets %}
<link href="{% static 'mie/css/miembros.css' %}" rel="stylesheet" type="text/css">
{% endblock stylesheets %}

{% block title %} Clientes {% endblock %}

{% block background %}{% static 'mie/img/cliente.jpg' %}{% endblock %}

{% block headers %}
<h1>Clientes</h1>
{% endblock %}

{% block content %}
<div class="member-section">
    <div id="alert-message" style="display: none;"></div>

    <form method="post" id="miembro-form">
        {% csrf_token %}
        <div class="form-group-container">
            <div class="form-group">
                <label for="nombre">Nombres:</label>
                <input type="text" id="nombre" name="nombre" class="form-control" required value="{{ nombre }}">
            </div>
            <div class="form-group">
                <label for="apellidos">Apellidos:</label>
                <input type="text" id="apellidos" name="apellidos" class="form-control" required value="{{ apellidos }}">
            </div>
        </div>

        <div class="form-group-container">
            <div class="select-group" style="margin-right: auto; ">
                <label for="genero">Género:</label>
                <select id="genero" name="genero" class="form-control" required>
                    <option value="" disabled selected>Selecciona un género</option>
                    {% for g in generos %}
                        <option value="{{ g.id }}">{{ g.nombre }}</option>
                    {% endfor %}
                </select>
            </div>
            
           
        </div>

        <div class="form-group-container">

            <div class="form-group">
                <label for="id">DPi:</label>
                <input type="text" id="di" name="di" class="form-control" required value="{{ di }}">
            </div>
        </div>

        <div class="form-group-container">
            <div class="form-group">
                <label for="telefono">Teléfono:</label>
                <input type="number" id="telefono" name="telefono" class="form-control" required>
            </div>
        </div>

        <div class="button-group">
            <button style= "cursor: pointer;" type="submit" class="btn btn-primary agregar-button">Agregar</button>
            <a href="{% url 'clientes:lista_cliente' %}" class="btn btn-primary listar-button">Listar</a>
        </div>
    </form>
</div>
{% endblock %}